### ISSUE TITLE
Looping through all the donations

### ISSUE THREAD

**Issue by nlmenghini** [BozarthPrime/Extra-Life-Tracker#12]
I really like the "last donation" widget but I'm curious if its possible to have it just keep looping through the donations. My js skills are pretty lacking.

If this is a potentially an easy addition I think it would be a great option in the settings file. Otherwise close out this issue.

Keep up the great work!

**Comment by ccrvincent** [comment]
> https://github.com/BozarthPrime/Extra-Life-Tracker#donation-rotation

Needs more <scroll> tag...
