### ISSUE TITLE
Last Donation widget needs to short-circuit on first API response

### ISSUE THREAD

**Issue by ccrvincent** [BozarthPrime/Extra-Life-Tracker#23]
For anyone with dozens (or in some cases, hundreds) of donations, the start-up time for the Last Donation widget is untenable.

Suggested fix: `checkForNewDonations` marks donations over a certain age as being seen already, or the API call leverages the `createdDateUTC` field as a filter.

`/donations?where=createdDateUTC%20>%202022-10-01`

**Comment by BozarthPrime** [comment]
Completed
